from .UIA import UserInterfaceAgent
from .PCA import PrescriptionConsultationAgent
from .MRA import MedicalRecordAgent
from .MPMA import MedicationProductManagementAgent
from .LRA import LaboratoryRadiologyAgent
from .AOA import AdmissionOrientationAgent
from .SCA import ServiceCoordinationAgent
from .PSEA import PatientSatisfactionEvaluationAgent
from .SAA import SecurityAccessAgent
from .MIA import MedicalIntelligenceAgent
from .ECA import ExternalCommunicationAgent
from .PLA import PlanningAgent
from .Patient import patient
